[package]
name = "frontend"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.83"
animation-lang = { git = "https://github.com/MabaKalox/animation-lang.git" }
getrandom = { version = "*", features = ["js"] }
