[package]
name = "std-esp-rust-lighting"
version = "0.1.0"
authors = ["maba_kalox <llocnex@gmail.com>"]
edition = "2021"
resolver = "2"

[profile.release]
opt-level = "s"

[profile.dev]
debug = true    # Symbols are nice and they don't increase the size on Flash
opt-level = "z"

[features]

[dependencies]
esp-idf-sys = { version = "0.31.11", features = ["binstart", "native"] }
esp-idf-svc = { version = "0.42.5", features = ["experimental"] }
esp-idf-hal = "0.38.1"
embedded-hal = "0.2.7"
embedded-svc = { version = "0.22.1" }
toml-cfg = "0.1.3"
anyhow = "1.0.65"
log = "0.4.17"
chrono = { version = "0.4.22", default-features = false, features = ["std"] }
smart-leds-trait = "0.2.1"
ws2812-esp32-rmt-driver = "0.4.0"
colorous = "1.0.8"
url = "2.3.1"
thiserror = "1.0.37"
serde_qs = "0.10.1"
serde = { version = "1.0.147", features = ["derive"] }
humantime-serde = "1.1.1"

[build-dependencies]
embuild = "0.30"
anyhow = "1"
